--Find total customers by countries
select
COUNT(customer_key) as total_customers
from .dim_customers
group by country
order by total_customers desc
--Find total customers by gender
select
gender,
COUNT(customer_key) as total_customers
from .dim_customers
group by gender
order by total_customers desc
--Find total product by category
select
category,
COUNT(product_key) as total_product
from .dim_products
group by category
order by total_product desc
--what is the average cost in each category?
select
category,
avg(cost) as avg_cost
from .dim_products
group by category
order by avg_cost desc

--what is the total revenue generated for each category?
select
p.category,
sum(f.sales_amount) as total_revenue
from .fact_sales f
left join .dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc
--Find total revenue is generated by each customer
select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from .fact_sales f
left join .dim_customers c
on c.customer_key = f.customer_key
group by
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc
--what is the distribution of sold items across countries?
select
c.country,
sum(f.quantity) as total_sold_items
from .fact_sales f
left join dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc